#!/usr/bin/env bash
# Generate Rust #[repr(C)] structs for CPython's _Py_DebugOffsets and
# Py_AsyncioModuleDebugOffsets using bindgen.
#
# Downloads the full CPython source, runs ./configure to generate pyconfig.h,
# then runs bindgen on the real headers. No manual extraction or sed parsing
# for the main debug offsets. The asyncio struct is extracted from
# Modules/_asynciomodule.c (where it is defined, not in a public header).
#
# Usage (run from kit/python_offsets/):
#   ./gen_debug_offsets.sh <cpython-git-ref> <module-name>
#
# Examples:
#   ./gen_debug_offsets.sh v3.14.0 py314
#   ./gen_debug_offsets.sh v3.13.0 py313
#
# Prerequisites: bindgen-cli (cargo install bindgen-cli), clang, curl

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <cpython-git-ref> <module-name>" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GIT_REF="$1"
MODULE="$2"
OUT="${SCRIPT_DIR}/../python_offsets_types/src/${MODULE}.rs"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# 1. Download CPython source
echo "Downloading CPython ${GIT_REF}..."
curl -sfL "https://github.com/python/cpython/archive/refs/tags/${GIT_REF}.tar.gz" \
    -o "$tmpdir/cpython.tar.gz" 2>/dev/null \
|| curl -sfL "https://github.com/python/cpython/archive/refs/heads/${GIT_REF}.tar.gz" \
    -o "$tmpdir/cpython.tar.gz"

mkdir -p "$tmpdir/cpython"
tar xzf "$tmpdir/cpython.tar.gz" --strip-components=1 -C "$tmpdir/cpython"

SRC="$tmpdir/cpython"

# 2. Run ./configure to generate pyconfig.h (no compilation, ~30s)
echo "Running ./configure..."
(cd "$SRC" && ./configure --disable-shared --without-ensurepip > /dev/null 2>&1)

# 3. Create a wrapper header that includes via Python.h (sets up all types)
#    then includes the internal header containing _Py_DebugOffsets.
INTERNAL_HEADER="internal/pycore_runtime.h"
if [ -f "$SRC/Include/internal/pycore_debug_offsets.h" ]; then
    INTERNAL_HEADER="internal/pycore_debug_offsets.h"
fi

cat > "$tmpdir/wrapper.h" <<EOF
#include "Python.h"
#include "${INTERNAL_HEADER}"
EOF

# 4. Run bindgen for _Py_DebugOffsets
echo "Running bindgen for _Py_DebugOffsets..."
bindgen "$tmpdir/wrapper.h" \
    --formatter=rustfmt \
    --allowlist-type '_Py_DebugOffsets' \
    --no-layout-tests \
    --no-doc-comments \
    --raw-line "// @generated by gen_debug_offsets.sh ${GIT_REF} ${MODULE}" \
    --raw-line "// DO NOT EDIT — re-run the generator instead." \
    --raw-line "// See kit/python_offsets/gen_debug_offsets.sh for details." \
    --raw-line "" \
    --raw-line "#![allow(non_camel_case_types)]" \
    --raw-line "" \
    --raw-line "//! CPython \`_Py_DebugOffsets\` layout for \`${GIT_REF}\`." \
    --raw-line "//!" \
    --raw-line "//! Auto-generated by \`gen_debug_offsets.sh ${GIT_REF} ${MODULE}\`." \
    --raw-line "//! Do not edit by hand." \
    -- -DPy_BUILD_CORE -I"$SRC" -I"$SRC/Include" -I"$SRC/Include/internal" \
    | sed 's/::std::os::raw::c_char/u8/g' \
    > "$OUT"

# 5. Extract Py_AsyncioModuleDebugOffsets from _asynciomodule.c (if present)
#    and run a second bindgen pass to append it to the same output file.
ASYNCIO_MODULE="$SRC/Modules/_asynciomodule.c"
if [ -f "$ASYNCIO_MODULE" ] && grep -q 'Py_AsyncioModuleDebugOffsets' "$ASYNCIO_MODULE"; then
    echo "Extracting Py_AsyncioModuleDebugOffsets from _asynciomodule.c..."

    # Extract the typedef block: from "typedef struct _Py_AsyncioModuleDebugOffsets {"
    # to the closing "} Py_AsyncioModuleDebugOffsets;"
    sed -n '/^typedef struct _Py_AsyncioModuleDebugOffsets/,/^} Py_AsyncioModuleDebugOffsets;/p' \
        "$ASYNCIO_MODULE" > "$tmpdir/asyncio_offsets.h"

    if [ -s "$tmpdir/asyncio_offsets.h" ]; then
        # Prepend stdint.h for uint64_t
        { echo '#include <stdint.h>'; cat "$tmpdir/asyncio_offsets.h"; } > "$tmpdir/asyncio_wrapper.h"

        echo "Running bindgen for Py_AsyncioModuleDebugOffsets..."
        bindgen "$tmpdir/asyncio_wrapper.h" \
            --formatter=rustfmt \
            --allowlist-type 'Py_AsyncioModuleDebugOffsets' \
            --no-layout-tests \
            --no-doc-comments \
            | sed 's/::std::os::raw::c_char/u8/g' \
            | grep -v '^/\* automatically generated' \
            >> "$OUT"

        echo "Appended Py_AsyncioModuleDebugOffsets to ${OUT}"
    else
        echo "Warning: could not extract Py_AsyncioModuleDebugOffsets typedef"
    fi
else
    echo "Note: Py_AsyncioModuleDebugOffsets not found in this CPython version (skipped)"
fi

echo "Generated ${OUT} from ${GIT_REF}"
