#!/usr/bin/env bash
# Generate Rust #[repr(C)] structs for CPython's _Py_DebugOffsets using bindgen.
#
# Downloads the full CPython source, runs ./configure to generate pyconfig.h,
# then runs bindgen on the real headers. No manual extraction or sed parsing.
#
# Usage (run from kit/python_offsets/):
#   ./gen_debug_offsets.sh <cpython-git-ref> <module-name>
#
# Examples:
#   ./gen_debug_offsets.sh v3.14.0 py314
#   ./gen_debug_offsets.sh v3.13.0 py313
#
# Prerequisites: bindgen-cli (cargo install bindgen-cli), clang, curl

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <cpython-git-ref> <module-name>" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GIT_REF="$1"
MODULE="$2"
OUT="${SCRIPT_DIR}/../python_offsets_types/src/${MODULE}.rs"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# 1. Download CPython source
echo "Downloading CPython ${GIT_REF}..."
curl -sfL "https://github.com/python/cpython/archive/refs/tags/${GIT_REF}.tar.gz" \
    -o "$tmpdir/cpython.tar.gz" 2>/dev/null \
|| curl -sfL "https://github.com/python/cpython/archive/refs/heads/${GIT_REF}.tar.gz" \
    -o "$tmpdir/cpython.tar.gz"

mkdir -p "$tmpdir/cpython"
tar xzf "$tmpdir/cpython.tar.gz" --strip-components=1 -C "$tmpdir/cpython"

SRC="$tmpdir/cpython"

# 2. Run ./configure to generate pyconfig.h (no compilation, ~30s)
echo "Running ./configure..."
(cd "$SRC" && ./configure --disable-shared --without-ensurepip > /dev/null 2>&1)

# 3. Create a wrapper header that includes via Python.h (sets up all types)
#    then includes the internal header containing _Py_DebugOffsets.
INTERNAL_HEADER="internal/pycore_runtime.h"
if [ -f "$SRC/Include/internal/pycore_debug_offsets.h" ]; then
    INTERNAL_HEADER="internal/pycore_debug_offsets.h"
fi

cat > "$tmpdir/wrapper.h" <<EOF
#include "Python.h"
#include "${INTERNAL_HEADER}"
EOF

# 4. Run bindgen
bindgen "$tmpdir/wrapper.h" \
    --allowlist-type '_Py_DebugOffsets' \
    --no-layout-tests \
    --no-doc-comments \
    --raw-line "//! CPython \`_Py_DebugOffsets\` layout for \`${GIT_REF}\`." \
    --raw-line "//!" \
    --raw-line "//! Auto-generated by \`gen_debug_offsets.sh ${GIT_REF} ${MODULE}\`." \
    --raw-line "//! Do not edit by hand." \
    -- -DPy_BUILD_CORE -I"$SRC" -I"$SRC/Include" -I"$SRC/Include/internal" \
    | sed 's/::std::os::raw::c_char/u8/g' \
    > "$OUT"

echo "Generated ${OUT} from ${GIT_REF}"
