/* Licensed under Apache-2.0 */

#ifndef PYROSCOPE_FFI_H_
#define PYROSCOPE_FFI_H_

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
  LastInstruction = 0,
  First = 1,
  NoLine = 2,
} LineNo;

bool initialize_logging(uint32_t logging_level);

/*
 # Safety
 All pointer arguments must be valid, non-null, null-terminated C strings.
 */
bool initialize_agent(const char *application_name,
                      const char *server_address,
                      const char *basic_auth_username,
                      const char *basic_auth_password,
                      uint32_t sample_rate,
                      bool oncpu,
                      bool gil_only,
                      bool report_pid,
                      bool report_thread_id,
                      bool report_thread_name,
                      const char *tags,
                      const char *tenant_id,
                      const char *http_headers_json,
                      LineNo line_no);

bool drop_agent(void);

/*
 # Safety
 `key` and `value` must be valid, non-null, null-terminated C strings.
 */
bool add_thread_tag(const char *key, const char *value);

/*
 # Safety
 `key` and `value` must be valid, non-null, null-terminated C strings.
 */
bool remove_thread_tag(const char *key, const char *value);

#endif  /* PYROSCOPE_FFI_H_ */
