FROM --platform=linux/aarch64 quay.io/pypa/manylinux2014_aarch64

# use musl rustup-init because gnu does not work on manylinux2010
# https://github.com/pyroscope-io/pyroscope-rs/pull/82#issuecomment-1434466795
# do same on manylinux2014 for consistency
RUN curl https://static.rust-lang.org/rustup/dist/aarch64-unknown-linux-musl/rustup-init -o ./rustup-init \
    && chmod +x ./rustup-init \
    && ./rustup-init  -y --default-toolchain=1.63.0 --default-host=aarch64-unknown-linux-gnu
ENV PATH=/root/.cargo/bin:$PATH
RUN yum -y install gcc libffi-devel openssl-devel wget

# for python
RUN wget https://github.com/libunwind/libunwind/releases/download/v1.6.2/libunwind-1.6.2.tar.gz \
    && tar -zxvf libunwind-1.6.2.tar.gz \
    && cd libunwind-1.6.2 \
    && ./configure --disable-minidebuginfo --enable-ptrace --disable-tests --disable-documentation \
    && make \
    && make install
