/* automatically generated by rust-bindgen 0.72.1 */

//! CPython `_Py_DebugOffsets` layout for `v3.14.0`.
//!
//! Auto-generated by `gen_debug_offsets.sh v3.14.0 py314`.
//! Do not edit by hand.

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets {
    pub cookie: [u8; 8usize],
    pub version: u64,
    pub free_threaded: u64,
    pub runtime_state: _Py_DebugOffsets__runtime_state,
    pub interpreter_state: _Py_DebugOffsets__interpreter_state,
    pub thread_state: _Py_DebugOffsets__thread_state,
    pub interpreter_frame: _Py_DebugOffsets__interpreter_frame,
    pub code_object: _Py_DebugOffsets__code_object,
    pub pyobject: _Py_DebugOffsets__pyobject,
    pub type_object: _Py_DebugOffsets__type_object,
    pub tuple_object: _Py_DebugOffsets__tuple_object,
    pub list_object: _Py_DebugOffsets__list_object,
    pub set_object: _Py_DebugOffsets__set_object,
    pub dict_object: _Py_DebugOffsets__dict_object,
    pub float_object: _Py_DebugOffsets__float_object,
    pub long_object: _Py_DebugOffsets__long_object,
    pub bytes_object: _Py_DebugOffsets__bytes_object,
    pub unicode_object: _Py_DebugOffsets__unicode_object,
    pub gc: _Py_DebugOffsets__gc,
    pub gen_object: _Py_DebugOffsets__gen_object,
    pub llist_node: _Py_DebugOffsets__llist_node,
    pub debugger_support: _Py_DebugOffsets__debugger_support,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__runtime_state {
    pub size: u64,
    pub finalizing: u64,
    pub interpreters_head: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__interpreter_state {
    pub size: u64,
    pub id: u64,
    pub next: u64,
    pub threads_head: u64,
    pub threads_main: u64,
    pub gc: u64,
    pub imports_modules: u64,
    pub sysdict: u64,
    pub builtins: u64,
    pub ceval_gil: u64,
    pub gil_runtime_state: u64,
    pub gil_runtime_state_enabled: u64,
    pub gil_runtime_state_locked: u64,
    pub gil_runtime_state_holder: u64,
    pub code_object_generation: u64,
    pub tlbc_generation: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__thread_state {
    pub size: u64,
    pub prev: u64,
    pub next: u64,
    pub interp: u64,
    pub current_frame: u64,
    pub thread_id: u64,
    pub native_thread_id: u64,
    pub datastack_chunk: u64,
    pub status: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__interpreter_frame {
    pub size: u64,
    pub previous: u64,
    pub executable: u64,
    pub instr_ptr: u64,
    pub localsplus: u64,
    pub owner: u64,
    pub stackpointer: u64,
    pub tlbc_index: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__code_object {
    pub size: u64,
    pub filename: u64,
    pub name: u64,
    pub qualname: u64,
    pub linetable: u64,
    pub firstlineno: u64,
    pub argcount: u64,
    pub localsplusnames: u64,
    pub localspluskinds: u64,
    pub co_code_adaptive: u64,
    pub co_tlbc: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__pyobject {
    pub size: u64,
    pub ob_type: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__type_object {
    pub size: u64,
    pub tp_name: u64,
    pub tp_repr: u64,
    pub tp_flags: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__tuple_object {
    pub size: u64,
    pub ob_item: u64,
    pub ob_size: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__list_object {
    pub size: u64,
    pub ob_item: u64,
    pub ob_size: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__set_object {
    pub size: u64,
    pub used: u64,
    pub table: u64,
    pub mask: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__dict_object {
    pub size: u64,
    pub ma_keys: u64,
    pub ma_values: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__float_object {
    pub size: u64,
    pub ob_fval: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__long_object {
    pub size: u64,
    pub lv_tag: u64,
    pub ob_digit: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__bytes_object {
    pub size: u64,
    pub ob_size: u64,
    pub ob_sval: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__unicode_object {
    pub size: u64,
    pub state: u64,
    pub length: u64,
    pub asciiobject_size: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__gc {
    pub size: u64,
    pub collecting: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__gen_object {
    pub size: u64,
    pub gi_name: u64,
    pub gi_iframe: u64,
    pub gi_frame_state: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__llist_node {
    pub next: u64,
    pub prev: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Py_DebugOffsets__debugger_support {
    pub eval_breaker: u64,
    pub remote_debugger_support: u64,
    pub remote_debugging_enabled: u64,
    pub debugger_pending_call: u64,
    pub debugger_script_path: u64,
    pub debugger_script_path_size: u64,
}
