/* Licensed under Apache-2.0 */

#ifndef RBSPY_H_
#define RBSPY_H_

/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

bool initialize_logging(uint32_t logging_level);

bool initialize_agent(const char *application_name,
                      const char *server_address,
                      const char *auth_token,
                      const char *basic_auth_user,
                      const char *basic_auth_password,
                      uint32_t sample_rate,
                      bool detect_subprocesses,
                      bool oncpu,
                      bool report_pid,
                      bool report_thread_id,
                      const char *tags,
                      const char *compression,
                      const char *_report_encoding,
                      const char *tenant_id,
                      const char *http_headers_json);

bool drop_agent(void);

bool add_thread_tag(uint64_t thread_id, const char *key, const char *value);

bool remove_thread_tag(uint64_t thread_id, const char *key, const char *value);

bool add_global_tag(const char *key, const char *value);

bool remove_global_tag(const char *key, const char *value);

#endif /* RBSPY_H_ */
