/* Licensed under Apache-2.0 */

#ifndef RBSPY_H_
#define RBSPY_H_

/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif /* RBSPY_H_ */
