FROM rust:latest@sha256:39d8cb39a54e7d1da665c4fabfdd265e532a5f836c11ab5aee27fd5c73891ce4

RUN apt-get update -qq \
 && apt-get install -y -qq --no-install-recommends \
      gcc-arm-linux-gnueabi \
      binutils-arm-linux-gnueabi \
      libc6-dev-armel-cross \
 && rm -rf /var/lib/apt/lists/*

RUN rustup target add arm-unknown-linux-gnueabi

ENV CC_arm_unknown_linux_gnueabi=arm-linux-gnueabi-gcc \
    AR_arm_unknown_linux_gnueabi=arm-linux-gnueabi-ar \
    CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABI_LINKER=arm-linux-gnueabi-gcc \
    CARGO_TARGET_DIR=/work/target/docker-arm

WORKDIR /work
