FROM rust:latest@sha256:a9cfb755b33f5bb872610cbdb25da61f527416b28fc9c052bbce4bef93e7799a

RUN apt-get update -qq \
 && apt-get install -y -qq --no-install-recommends \
      gcc-arm-linux-gnueabi \
      binutils-arm-linux-gnueabi \
      libc6-dev-armel-cross \
 && rm -rf /var/lib/apt/lists/*

RUN rustup target add arm-unknown-linux-gnueabi

ENV CC_arm_unknown_linux_gnueabi=arm-linux-gnueabi-gcc \
    AR_arm_unknown_linux_gnueabi=arm-linux-gnueabi-ar \
    CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABI_LINKER=arm-linux-gnueabi-gcc \
    CARGO_TARGET_DIR=/work/target/docker-arm

WORKDIR /work
