detect_subprocesses = false 
log_level = "info"
no_logging = false
blocking = false
oncpu = false
pyspy_gil = false
pyspy_native = false
sample_rate = 100
server_address = "http://localhost:4040"
auth_token = ""
basic_auth_username = ""
basic_auth_password = ""
debug = false
