# frozen_string_literal: true

require 'rake/extensiontask'

load File.expand_path('./ext/thread_id/Rakefile', __dir__)
load File.expand_path('./ext/rbspy/Rakefile', __dir__)

task default: %w[hello]

task :hello do
  puts 'Hello!'
end

Rake::ExtensionTask.new('thread_id')
Rake::ExtensionTask.new('rbspy')
